import streamlit as st
import pandas as pd
from backend_data import load_water_data, get_scenario_data

# Page Configuration
st.set_page_config(
    page_title="JalSathi AI - Intelligent Water Command Center",
    page_icon="💧",
    layout="wide",
    initial_sidebar_state="expanded"
)

# App Header
st.title("💧 JalSathi AI: Intelligent Water Management & Early Warning System")
st.markdown("Empowering local authorities and communities with real-time water risk insights, predictive flood alerts, and automated leak detection.")

# --- TOP-LEVEL ENTERPRISE METRICS BANNER ---
df_metrics = load_water_data()
m1, m2, m3 = st.columns(3)
with m1:
    st.metric(label="Active Monitored Regions", value=len(df_metrics))
with m2:
    st.metric(label="Critical Alerts Active", value=str(len(df_metrics[df_metrics['risk_level'] == 'HIGH'])) + " Zones")
with m3:
    st.metric(label="AI Intelligence Core", value="Online (Gemini 3.7 Flash)")

st.markdown("---")

# Sidebar for Quick Scenarios
st.sidebar.header("🔍 Quick Scenario Test")
scenario_option = st.sidebar.selectbox(
    "Choose a demo scenario:",
    ["Select...", "Assam Flood Alert", "Mandya Drought Watch", "Indore Pipeline Leakage"]
)

st.sidebar.markdown("---")
st.sidebar.info("💡 **Hackathon Tip:** Use the query box or quick scenarios to trigger real-time AI strategic action plans.")

# Main Dashboard Layout
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader("💬 Ask JalSathi AI")
    user_query = st.text_input("Type your water query (e.g., 'Check flood risk in Assam'):")
    
    # Handle sidebar quick select overrides
    if scenario_option == "Assam Flood Alert":
        user_query = "Assam flood"
    elif scenario_option == "Mandya Drought Watch":
        user_query = "Mandya drought"
    elif scenario_option == "Indore Pipeline Leakage":
        user_query = "Indore leakage"
        
    if user_query:
        st.markdown(f"**Analyzing query:** *'{user_query}'*")
        data = get_scenario_data(user_query)
        
        # Display Results in Cards
        st.info(f"📍 **Region:** {data['region']} | **Scenario:** {data['scenario'].upper()}")
        
        metric_col1, metric_col2, metric_col3 = st.columns(3)
        with metric_col1:
            st.metric(label="Primary Indicator", value=data['primary_indicator'])
        with metric_col2:
            st.metric(label="Current Value", value=data['current_value'])
        with metric_col3:
            st.metric(label="Threshold Limit", value=data['threshold_limit'])
            
        if data['risk_level'] == 'HIGH':
            st.error(f"⚠️ **Risk Level: HIGH** - Immediate action recommended for {data['region']}!")
        else:
            st.warning(f"⚠️ **Risk Level: MEDIUM** - Monitor conditions closely.")
            
        # Display Gemini AI Strategic Directive
        if 'ai_recommendation' in data:
            st.success(f"🤖 **JalSathi AI Strategic Directive:** {data['ai_recommendation']}")
            
            # Export Action Plan Button
            report_text = f"""JALSAATHI AI - EMERGENCY ACTION REPORT
----------------------------------------------
Region: {data['region']}
Scenario: {data['scenario'].upper()}
Risk Level: {data['risk_level']}
Indicator: {data['primary_indicator']} (Current: {data['current_value']} | Limit: {data['threshold_limit']})

AI STRATEGIC DIRECTIVE:
{data['ai_recommendation']}
----------------------------------------------
Generated by JalSathi AI Intelligent Water Management System.
"""
            st.download_button(
                label="📥 Download Official Emergency Directive (TXT)",
                data=report_text,
                file_name=f"JalSathi_Report_{data['region']}.txt",
                mime="text/plain"
            )

    # --- ELITE ADDITION: Interactive Live Stress-Tester Slider ---
    st.markdown("---")
    st.subheader("🎛️ Live Scenario Stress-Tester")
    simulated_level = st.slider("Simulate Threshold / Water Volume Value:", min_value=10.0, max_value=400.0, value=float(df_metrics['current_value'].iloc[0]))
    
    if simulated_level > 200.0:
        st.error(f"🚨 **AUTOMATED OVERFLOW ALERT:** At value `{simulated_level}`, emergency flood gates and regional diversion pumps engage automatically.")
    else:
        st.success(f"✅ **SYSTEM NOMINAL:** Operational volume at `{simulated_level}` is well within safe thresholds.")

with col2:
    st.subheader("📊 Live Simulation Data")
    df = load_water_data()
    st.dataframe(df, width="stretch")

# Footer
st.markdown("---")
st.caption("JalSathi AI Hackathon Prototype — Powered by Python, Streamlit, and Gemini 3.7 Flash")